apiVersion: v1
kind: Pod
metadata:
  name: srv
spec:
  serviceAccountName: pod-exec
  containers:
  - name: srv
    image: docker.io/dmitsh/k8sutils:0.1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
