apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: ubuntu:22.04
    imagePullPolicy: Always        
    command:
    - /bin/bash
    args:
    - -c
    - 'while true ; do echo "ping"; sleep 10; done'
    volumeMounts:
    - name: data-volume
      mountPath: /etc/test
  volumes:
  - name: data-volume
    configMap:
      name: data-configmap
  restartPolicy: Never
