apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-exec
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-exec
  namespace: default
roleRef:
  kind: Role
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io
